[default]
account = "SDWZHHA-LIB23322"
user = "PRANAVKOLH"
private_key_file = "eyJraWQiOiI3OTI0MDcyOTI3NDIwNDIyIiwiYWxnIjoiRVMyNTYifQ.eyJwIjoiNDcyMzExNTU2OjQ3MjMxMTU1NiIsImlzcyI6IlNGOjEwNDkiLCJleHAiOjE4MDI1MjM3NzR9.w4vpoT1SKFcCdHql1dvjyJz5ZOcJHKxLcmlW0OLZk0q3YdES1pnt0KzY6g0u3U8Ls9e2SHaMqNZ2OCYLaS7AeA"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"


